"""
Phase 6: US Jurisdiction Clauses
Creates 66 US clause variants (22 clause types × 3 variants) with
US-specific legal language, statute references, and parameters.
"""

from neo4j import GraphDatabase
from dotenv import load_dotenv
import os

load_dotenv()
driver = GraphDatabase.driver(
    os.getenv("NEO4J_URI"),
    auth=(os.getenv("NEO4J_USERNAME"), os.getenv("NEO4J_PASSWORD"))
)

US_CLAUSES = [
    # ===== CONFIDENTIALITY =====
    {"id": "CONF_STD_US001", "clause_type": "confidentiality", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "CONFIDENTIALITY\n\n1. DEFINITION\n\"Confidential Information\" means any non-public information disclosed by either Party in connection with this Agreement, whether oral, written, or electronic.\n\n2. OBLIGATIONS\nThe Receiving Party shall: (a) hold Confidential Information in strict confidence; (b) not disclose it to any third party without prior written consent; (c) use it solely for purposes of this Agreement.\n\n3. EXCLUSIONS\nConfidential Information does not include information that: (a) is or becomes publicly available without breach; (b) was known prior to disclosure; (c) is independently developed; (d) is received from a third party without restriction.\n\n4. DURATION\nConfidentiality obligations survive for {{CONFIDENTIALITY_PERIOD}} years after termination.\n\n5. REMEDIES\nThe Receiving Party acknowledges that breach may cause irreparable harm and the Disclosing Party shall be entitled to seek equitable relief including injunctive relief under applicable federal or state law."},

    {"id": "CONF_MOD_US001", "clause_type": "confidentiality", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "CONFIDENTIALITY\n\n1. DEFINED CATEGORIES\n\"Confidential Information\" includes: (a) Trade Secrets as defined under the Defend Trade Secrets Act of 2016 (18 U.S.C. §1836); (b) business plans, financial data, customer lists; (c) technical specifications, source code, algorithms; (d) any information marked \"Confidential\" or disclosed under circumstances indicating confidentiality.\n\n2. BILATERAL OBLIGATIONS\nEach Party shall: (a) protect Confidential Information with at least the same degree of care as its own (but no less than reasonable care); (b) limit access to employees and agents with a need-to-know who are bound by written confidentiality obligations; (c) promptly notify the Disclosing Party of any unauthorized disclosure.\n\n3. COMPELLED DISCLOSURE\nIf compelled by subpoena, court order, or regulatory requirement, the Receiving Party shall: (a) provide prompt written notice; (b) cooperate with efforts to obtain a protective order; (c) disclose only the minimum required.\n\n4. RETURN AND DESTRUCTION\nUpon termination or request, the Receiving Party shall return or destroy all Confidential Information and provide written certification within {{RETURN_PERIOD_DAYS}} days.\n\n5. SURVIVAL\nObligations survive for {{CONFIDENTIALITY_PERIOD}} years; trade secrets are protected indefinitely under DTSA."},

    {"id": "CONF_STR_US001", "clause_type": "confidentiality", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "CONFIDENTIALITY\n\n1. BROAD DEFINITION\n\"Confidential Information\" encompasses all non-public information exchanged in any form, including Trade Secrets (18 U.S.C. §1836), proprietary technology, algorithms, business strategies, financial projections, and any information a reasonable person would consider confidential.\n\n2. ENHANCED PROTECTIONS\nThe Receiving Party shall: (a) implement industry-standard security controls (encryption, access controls, audit logging); (b) restrict access to personnel who have executed individual NDAs; (c) maintain a log of all persons accessing Confidential Information; (d) not reverse engineer, decompile, or disassemble any Confidential Information.\n\n3. INJUNCTIVE RELIEF\nThe Parties acknowledge that monetary damages may be insufficient. The Disclosing Party shall be entitled to seek temporary restraining orders, preliminary and permanent injunctive relief in any court of competent jurisdiction without bond, in addition to all other remedies at law or equity.\n\n4. DTSA NOTICE\nPursuant to 18 U.S.C. §1833(b)(1), an individual shall not be held criminally or civilly liable under any federal or state trade secret law for disclosure of a trade secret made in confidence to a government official or attorney solely for reporting a suspected violation of law.\n\n5. SURVIVAL\nConfidentiality obligations are perpetual for Trade Secrets and survive {{CONFIDENTIALITY_PERIOD}} years for all other Confidential Information."},

    # ===== DEFINITIONS =====
    {"id": "DEFN_STD_US001", "clause_type": "definitions", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "DEFINITIONS\n\nIn this Agreement, unless the context requires otherwise:\n\n\"Affiliate\" means any entity that directly or indirectly controls, is controlled by, or is under common control with a Party.\n\"Agreement\" means this agreement including all exhibits, schedules, and amendments.\n\"Business Day\" means any day other than a Saturday, Sunday, or federal holiday in the United States.\n\"Effective Date\" means the date set forth in the preamble.\n\"Party\" and \"Parties\" means {{PARTY_A_NAME}} and {{PARTY_B_NAME}}, individually or collectively.\n\"Services\" means the services described in {{SERVICES_DESCRIPTION}}.\n\"Term\" means the period set forth in the Term and Renewal clause."},

    {"id": "DEFN_MOD_US001", "clause_type": "definitions", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "DEFINITIONS\n\nIn this Agreement:\n\n\"Affiliate\" means any entity controlling, controlled by, or under common control with a Party, where \"control\" means ownership of 50%+ of voting securities.\n\"Agreement\" means this agreement and all Exhibits, Schedules, SOWs, and amendments.\n\"Business Day\" means Monday through Friday, excluding U.S. federal holidays.\n\"Change of Control\" means any merger, acquisition, or sale of substantially all assets.\n\"Confidential Information\" has the meaning set forth in the Confidentiality clause.\n\"Deliverables\" means the work product specified in each SOW.\n\"Effective Date\" means the date first written above.\n\"Force Majeure Event\" has the meaning set forth in the Force Majeure clause.\n\"Indemnified Party\" and \"Indemnifying Party\" have the meanings in the Indemnification clause.\n\"Intellectual Property\" means all patents, copyrights, trademarks, trade secrets, and other IP rights.\n\"Laws\" means all applicable federal, state, and local statutes, regulations, and ordinances.\n\"Losses\" means damages, liabilities, costs, and expenses including reasonable attorneys' fees.\n\"Party\" means {{PARTY_A_NAME}} or {{PARTY_B_NAME}}.\n\"Services\" means {{SERVICES_DESCRIPTION}}.\n\"SOW\" or \"Statement of Work\" means a document describing specific services, deliverables, and fees."},

    {"id": "DEFN_STR_US001", "clause_type": "definitions", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "DEFINITIONS AND INTERPRETATION\n\n1. DEFINITIONS\n\"Affiliate\" means any entity directly or indirectly controlling, controlled by, or under common control with a Party (\"control\" = 50%+ voting power or equivalent).\n\"Applicable Law\" means all federal, state, local, and foreign laws, statutes (including UCC), regulations, orders, and ordinances.\n\"Business Day\" means Monday-Friday excluding U.S. federal holidays and the period between December 25 and January 1.\n\"Change of Control\" means (a) merger/consolidation; (b) sale of >50% voting securities; (c) sale of all/substantially all assets.\n\"Claim\" means any third-party claim, demand, suit, or proceeding.\n\"Confidential Information\" — see Confidentiality clause.\n\"Consequential Damages\" means indirect, incidental, special, exemplary, or punitive damages, lost profits, and lost revenue.\n\"Effective Date\" means the date of last signature.\n\"Governmental Authority\" means any federal, state, local, or foreign government or regulatory body.\n\"IP Rights\" means all patents, copyrights, trademarks, trade secrets, moral rights, and rights of publicity.\n\"Material Adverse Effect\" means any event that materially impairs a Party's ability to perform.\n\"Person\" means any individual, corporation, LLC, partnership, trust, or governmental entity.\n\n2. INTERPRETATION\n(a) Headings are for convenience only.\n(b) \"Including\" means \"including without limitation.\"\n(c) References to statutes include amendments and successor legislation.\n(d) Exhibits, Schedules, and SOWs are incorporated by reference.\n(e) In case of conflict: (i) amendments prevail; (ii) main body over exhibits; (iii) later SOW over earlier."},

    # ===== GOVERNING LAW =====
    {"id": "GOV_STD_US001", "clause_type": "governing-law-and-jurisdiction", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "GOVERNING LAW AND JURISDICTION\n\nThis Agreement shall be governed by and construed in accordance with the laws of the State of {{GOVERNING_STATE}}, without regard to its conflict of laws principles. Each Party irrevocably submits to the exclusive jurisdiction of the federal and state courts located in {{COURT_LOCATION}} for any dispute arising out of this Agreement."},

    {"id": "GOV_MOD_US001", "clause_type": "governing-law-and-jurisdiction", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "GOVERNING LAW AND JURISDICTION\n\n1. GOVERNING LAW\nThis Agreement is governed by the laws of the State of {{GOVERNING_STATE}}, excluding its conflict of laws rules. The United Nations Convention on Contracts for the International Sale of Goods (CISG) is expressly excluded.\n\n2. DISPUTE RESOLUTION\nAny dispute shall be resolved by binding arbitration administered by the American Arbitration Association (AAA) under its Commercial Arbitration Rules. The arbitration shall be conducted in {{ARBITRATION_CITY}}, {{GOVERNING_STATE}} by a single arbitrator.\n\n3. PROVISIONAL REMEDIES\nNotwithstanding the arbitration provision, either Party may seek injunctive or other provisional relief from any court of competent jurisdiction to prevent irreparable harm.\n\n4. PREVAILING PARTY\nThe prevailing party in any arbitration or litigation shall be entitled to recover reasonable attorneys' fees and costs."},

    {"id": "GOV_STR_US001", "clause_type": "governing-law-and-jurisdiction", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "GOVERNING LAW AND JURISDICTION\n\n1. GOVERNING LAW\nThis Agreement is governed by the laws of the State of {{GOVERNING_STATE}} without regard to conflict of laws principles. The CISG and Uniform Computer Information Transactions Act (UCITA) are excluded.\n\n2. ARBITRATION\nAll disputes shall be resolved by binding arbitration under the AAA Commercial Rules or JAMS Comprehensive Rules (at Claimant's election). Arbitration shall be conducted in {{ARBITRATION_CITY}} by a panel of three arbitrators with relevant industry expertise.\n\n3. ARBITRATION PROCEDURES\n(a) Discovery shall be limited to document production and depositions;\n(b) The arbitrators shall issue a reasoned written award;\n(c) Judgment on the award may be entered in any court under the Federal Arbitration Act (9 U.S.C. §1 et seq.);\n(d) Each Party bears its own costs; the losing party bears arbitration administrative fees.\n\n4. EMERGENCY RELIEF\nPursuant to AAA Emergency Measures of Protection, either Party may seek emergency interim relief prior to panel constitution.\n\n5. CLASS ACTION WAIVER\nEach Party waives any right to participate in a class action, class arbitration, or representative proceeding."},

    # ===== DISPUTE RESOLUTION =====
    {"id": "DISP_STD_US001", "clause_type": "dispute-resolution", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "DISPUTE RESOLUTION\n\nAny dispute arising under this Agreement shall be submitted to the exclusive jurisdiction of the federal and state courts located in {{COURT_LOCATION}}, {{GOVERNING_STATE}}. Each Party waives any objection to venue and personal jurisdiction. Process may be served by certified mail, return receipt requested."},

    {"id": "DISP_MOD_US001", "clause_type": "dispute-resolution", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "DISPUTE RESOLUTION\n\n1. ESCALATION\nThe Parties shall first attempt to resolve disputes through good-faith negotiation between senior executives for {{NEGOTIATION_PERIOD_DAYS}} days.\n\n2. MEDIATION\nIf negotiation fails, the Parties shall submit to non-binding mediation under the AAA Mediation Rules for {{MEDIATION_PERIOD_DAYS}} days.\n\n3. ARBITRATION\nIf mediation fails, disputes shall be resolved by binding arbitration under AAA Commercial Rules in {{ARBITRATION_CITY}}.\n\n4. CONTINUED PERFORMANCE\nPending resolution, the Parties shall continue performing their obligations except for the disputed matter.\n\n5. EQUITABLE RELIEF\nNothing herein prevents either Party from seeking injunctive relief to prevent irreparable harm."},

    {"id": "DISP_STR_US001", "clause_type": "dispute-resolution", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "DISPUTE RESOLUTION\n\n1. MANDATORY ESCALATION\n(a) Written notice specifying the dispute in detail;\n(b) Executive negotiation: {{NEGOTIATION_PERIOD_DAYS}} days between C-level executives;\n(c) Mediation: AAA or JAMS mediation for {{MEDIATION_PERIOD_DAYS}} days.\n\n2. BINDING ARBITRATION\nIf unresolved, final and binding arbitration under JAMS Comprehensive Rules. Three-arbitrator panel in {{ARBITRATION_CITY}}. Discovery permitted: document production, 3 depositions per side, expert reports. Reasoned written award within 60 days of hearing close.\n\n3. EMERGENCY ARBITRATOR\nPursuant to JAMS Emergency Relief Procedures, either Party may apply for emergency interim measures.\n\n4. CONFIDENTIALITY OF PROCEEDINGS\nAll arbitration proceedings, evidence, and awards shall be confidential.\n\n5. ENFORCEMENT\nThe award is final and enforceable under the Federal Arbitration Act. Judgment may be entered in any court of competent jurisdiction.\n\n6. FEES\nThe losing Party shall bear all arbitration fees. Each Party bears its own attorneys' fees unless the arbitrator determines a claim was frivolous."},

    # ===== PAYMENT TERMS =====
    {"id": "PAY_STD_US001", "clause_type": "payment-terms", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "PAYMENT TERMS\n\n1. FEES\n{{PARTY_B_NAME}} shall pay {{PARTY_A_NAME}} the fees set forth in the applicable SOW or Schedule.\n\n2. INVOICING\nInvoices shall be issued {{INVOICE_FREQUENCY}} and are payable within {{PAYMENT_DAYS}} days of receipt. All amounts are in US Dollars (USD).\n\n3. TAXES\nAll fees are exclusive of applicable sales, use, and excise taxes. {{PARTY_B_NAME}} is responsible for all taxes except {{PARTY_A_NAME}}'s income taxes.\n\n4. LATE PAYMENT\nOverdue amounts shall bear interest at the lesser of 1.5% per month or the maximum rate permitted by applicable law."},

    {"id": "PAY_MOD_US001", "clause_type": "payment-terms", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "PAYMENT TERMS\n\n1. FEES AND INVOICING\nFees are as set forth in each SOW. Invoices are due Net {{PAYMENT_DAYS}} from invoice date. All payments in USD by wire transfer or ACH to the designated account.\n\n2. EXPENSES\nReasonable pre-approved expenses are reimbursable within {{EXPENSE_SUBMISSION_DAYS}} days of incurrence, supported by receipts.\n\n3. TAXES\nFees exclude all sales, use, VAT, and withholding taxes. {{PARTY_B_NAME}} shall gross up payments to ensure {{PARTY_A_NAME}} receives the full invoiced amount after any required withholding (IRS Form W-9/W-8BEN to be provided).\n\n4. LATE PAYMENT\nOverdue amounts accrue interest at {{LATE_INTEREST_RATE}}% per month. If payment is more than {{PAYMENT_DEFAULT_DAYS}} days overdue, {{PARTY_A_NAME}} may suspend Services upon {{SUSPENSION_NOTICE_DAYS}} days' written notice.\n\n5. DISPUTE\nPayment disputes must be raised in writing within {{INVOICE_DISPUTE_DAYS}} days of invoice receipt. Undisputed amounts remain payable on schedule."},

    {"id": "PAY_STR_US001", "clause_type": "payment-terms", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "PAYMENT TERMS\n\n1. MILESTONE PAYMENTS\nPayment shall be milestone-based as set forth in each SOW. Milestone acceptance triggers payment obligation. Invoices due Net {{PAYMENT_DAYS}}.\n\n2. ESCROW\nFor contracts exceeding ${{ESCROW_THRESHOLD}}, {{ESCROW_PERCENTAGE}}% of total fees shall be held in escrow with {{ESCROW_AGENT}} and released upon final milestone acceptance.\n\n3. TAX COMPLIANCE\nAll applicable federal, state, and local taxes are {{PARTY_B_NAME}}'s responsibility. 1099-NEC/1099-MISC reporting obligations are acknowledged. Withholding under IRC §3406 applies if W-9 is not timely provided.\n\n4. LATE PAYMENT AND REMEDIES\n(a) Interest: {{LATE_INTEREST_RATE}}% per month on overdue amounts;\n(b) Late fee: ${{LATE_FEE_AMOUNT}} or {{LATE_FEE_PERCENTAGE}}% of overdue amount, whichever is greater;\n(c) Suspension: automatic suspension after {{PAYMENT_DEFAULT_DAYS}} days overdue;\n(d) Acceleration: all future milestones become immediately due upon second payment default.\n\n5. AUDIT\n{{PARTY_A_NAME}} may audit {{PARTY_B_NAME}}'s usage/fee records annually with {{AUDIT_NOTICE_DAYS}} days' notice. If audit reveals underpayment >5%, {{PARTY_B_NAME}} bears audit costs.\n\n6. SET-OFF\nNeither Party may set off amounts owed under this Agreement against amounts owed under other agreements without written consent."},

    # ===== SCOPE OF AGREEMENT =====
    {"id": "SCOP_STD_US001", "clause_type": "scope-of-agreement", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "SCOPE OF AGREEMENT\n\n1. SERVICES\n{{PARTY_A_NAME}} shall provide the services described in {{SERVICES_DESCRIPTION}} (the \"Services\") to {{PARTY_B_NAME}}.\n\n2. STANDARD OF PERFORMANCE\nServices shall be performed in a professional and workmanlike manner consistent with generally accepted industry standards.\n\n3. INDEPENDENT CONTRACTOR\n{{PARTY_A_NAME}} is an independent contractor. Nothing in this Agreement creates an employment, partnership, joint venture, or agency relationship. {{PARTY_A_NAME}} is responsible for its own taxes, insurance, and benefits."},

    {"id": "SCOP_MOD_US001", "clause_type": "scope-of-agreement", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "SCOPE OF AGREEMENT\n\n1. SERVICES AND SOW FRAMEWORK\nServices are defined in individual Statements of Work (SOWs) executed under this Agreement. Each SOW shall specify: scope, deliverables, milestones, fees, and acceptance criteria.\n\n2. CHANGE ORDERS\nChanges to scope require a written Change Order signed by both Parties specifying the impact on timeline, deliverables, and fees.\n\n3. ACCEPTANCE TESTING\nDeliverables are subject to acceptance testing per SOW criteria. {{PARTY_B_NAME}} shall notify acceptance or rejection with specific deficiencies within {{ACCEPTANCE_PERIOD_DAYS}} days. Failure to respond constitutes acceptance.\n\n4. INDEPENDENT CONTRACTOR STATUS\n{{PARTY_A_NAME}} is an independent contractor, not an employee. {{PARTY_A_NAME}} controls the manner and means of performance. No benefits, workers' compensation, or unemployment insurance are provided.\n\n5. EXCLUSIVITY\nThis Agreement is non-exclusive. Both Parties retain the right to engage with third parties for similar services."},

    {"id": "SCOP_STR_US001", "clause_type": "scope-of-agreement", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "SCOPE OF AGREEMENT\n\n1. DETAILED SOW FRAMEWORK\nAll Services are governed by executed SOWs. Each SOW incorporates this Agreement's terms and specifies: (a) detailed scope and exclusions; (b) deliverables with specifications; (c) milestones and deadlines; (d) assigned personnel; (e) SLAs with metrics; (f) fees and payment schedule.\n\n2. SERVICE LEVELS\n{{PARTY_A_NAME}} shall meet SLAs specified in each SOW, including: uptime of {{UPTIME_SLA}}%, response time of {{RESPONSE_TIME}}, resolution targets per severity level. Service credits apply for SLA breaches.\n\n3. CHANGE CONTROL\nNo changes without a signed Change Order. Unauthorized work performed is at {{PARTY_A_NAME}}'s risk and expense.\n\n4. ACCEPTANCE PROCESS\n(a) Submit deliverables with completion certificate;\n(b) {{PARTY_B_NAME}} tests within {{ACCEPTANCE_PERIOD_DAYS}} days;\n(c) Rejection requires written deficiency list;\n(d) {{PARTY_A_NAME}} remediates within {{REMEDY_PERIOD_DAYS}} days;\n(e) Second rejection entitles {{PARTY_B_NAME}} to terminate the SOW.\n\n5. PERSONNEL\nKey personnel identified in SOW may not be reassigned without {{PARTY_B_NAME}}'s consent. Replacements must have equivalent qualifications.\n\n6. INDEPENDENT CONTRACTOR\n{{PARTY_A_NAME}} acknowledges independent contractor status per IRS guidelines (common law test / ABC test where applicable)."},

    # ===== TERM AND RENEWAL =====
    {"id": "TERM_STD_US001", "clause_type": "term-and-renewal", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "TERM AND RENEWAL\n\n1. INITIAL TERM\nThis Agreement commences on {{START_DATE}} and continues for {{TERM_DURATION}} (the \"Initial Term\").\n\n2. RENEWAL\nThis Agreement automatically renews for successive {{RENEWAL_TERM_DURATION}} periods unless either Party provides written notice of non-renewal at least {{NOTICE_PERIOD}} days prior to the end of the then-current term.\n\n3. EFFECT OF EXPIRATION\nExpiration does not release either Party from obligations accrued prior to expiration."},

    {"id": "TERM_MOD_US001", "clause_type": "term-and-renewal", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "TERM AND RENEWAL\n\n1. INITIAL TERM\nThe Agreement is effective from {{START_DATE}} through {{END_DATE}} (the \"Initial Term\").\n\n2. AUTO-RENEWAL\nThe Agreement renews automatically for successive {{RENEWAL_TERM_DURATION}} periods unless either Party provides non-renewal notice at least {{RENEWAL_NOTICE_PERIOD}} days before expiration.\n\n3. PRICE ADJUSTMENTS\nUpon renewal, fees may increase by up to {{PRICE_ADJUSTMENT_PERCENTAGE}}% or the Consumer Price Index (CPI-U) increase, whichever is lower, with {{PRICE_NOTICE_DAYS}} days' prior notice.\n\n4. TRANSITION\nUpon non-renewal, {{PARTY_A_NAME}} shall provide reasonable transition assistance for up to {{TRANSITION_DAYS}} days at then-current rates."},

    {"id": "TERM_STR_US001", "clause_type": "term-and-renewal", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "TERM AND RENEWAL\n\n1. TERM\nEffective {{START_DATE}} through {{END_DATE}}, subject to minimum commitment of {{MINIMUM_COMMITMENT}}.\n\n2. RENEWAL\n(a) Auto-renewal for {{RENEWAL_TERM_DURATION}} periods;\n(b) Non-renewal notice: {{RENEWAL_NOTICE_PERIOD}} days;\n(c) Renewal acceptance window: {{RENEWAL_ACCEPTANCE_WINDOW_DAYS}} days.\n\n3. PRICE ESCALATION\nRenewal pricing subject to annual escalation up to {{PRICE_ADJUSTMENT_PERCENTAGE}}% with {{PRICE_NOTICE_DAYS}} days' notice.\n\n4. HOLDOVER\nIf either Party continues performance after expiration without renewal: (a) the Agreement continues month-to-month at {{HOLDOVER_RATE_MULTIPLIER}}x the then-current rates; (b) either Party may terminate the holdover period on {{HOLDOVER_TERMINATION_NOTICE}} days' notice.\n\n5. EARLY TERMINATION\nTermination before minimum commitment triggers early termination fee per the Termination clause."},

    # ===== INTELLECTUAL PROPERTY =====
    {"id": "IP_STD_US001", "clause_type": "intellectual-property-ownership", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "INTELLECTUAL PROPERTY OWNERSHIP\n\n1. WORK PRODUCT\nAll work product, deliverables, and materials created by {{PARTY_A_NAME}} in performance of this Agreement (\"Work Product\") shall be the exclusive property of {{PARTY_B_NAME}}.\n\n2. ASSIGNMENT\n{{PARTY_A_NAME}} hereby assigns to {{PARTY_B_NAME}} all right, title, and interest in the Work Product, including all copyrights, patents, and trade secrets.\n\n3. WORK MADE FOR HIRE\nTo the extent permitted under 17 U.S.C. §101, all copyrightable Work Product is \"work made for hire.\" To the extent any Work Product does not qualify, {{PARTY_A_NAME}} assigns all rights.\n\n4. FURTHER ASSURANCES\n{{PARTY_A_NAME}} shall execute all documents necessary to perfect {{PARTY_B_NAME}}'s ownership."},

    {"id": "IP_MOD_US001", "clause_type": "intellectual-property-ownership", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "INTELLECTUAL PROPERTY OWNERSHIP\n\n1. BACKGROUND IP\nEach Party retains all rights to its pre-existing intellectual property (\"Background IP\"). Background IP is identified in Schedule {{IP_SCHEDULE}}.\n\n2. FOREGROUND IP\nAll IP created specifically for {{PARTY_B_NAME}} under this Agreement (\"Foreground IP\") is assigned to {{PARTY_B_NAME}} under 17 U.S.C. §101 (work made for hire) or by assignment.\n\n3. LICENSE TO BACKGROUND IP\n{{PARTY_A_NAME}} grants {{PARTY_B_NAME}} a non-exclusive, perpetual, royalty-free license to use {{PARTY_A_NAME}}'s Background IP solely to the extent embedded in Foreground IP.\n\n4. JOINT IP\nAny IP created jointly shall be jointly owned, with each Party having the right to exploit without accounting to the other, unless otherwise agreed in the applicable SOW.\n\n5. MORAL RIGHTS\nTo the extent permitted by law, {{PARTY_A_NAME}} waives all moral rights in the Work Product under the Visual Artists Rights Act (17 U.S.C. §106A) and equivalent state laws."},

    {"id": "IP_STR_US001", "clause_type": "intellectual-property-ownership", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "INTELLECTUAL PROPERTY OWNERSHIP\n\n1. DEFINITION OF IP RIGHTS\n\"IP Rights\" means all worldwide rights in patents, copyrights, trademarks, trade secrets, mask works, moral rights, rights of publicity, and all applications and registrations thereof.\n\n2. WORK MADE FOR HIRE AND ASSIGNMENT\n(a) All Work Product is \"work made for hire\" under 17 U.S.C. §101;\n(b) To the extent any Work Product fails to qualify, {{PARTY_A_NAME}} irrevocably assigns all IP Rights to {{PARTY_B_NAME}};\n(c) Assignment includes all rights to file, prosecute, and enforce patents worldwide;\n(d) {{PARTY_A_NAME}} shall execute assignments, declarations, and USPTO/foreign filings as requested.\n\n3. INVENTION DISCLOSURE\n{{PARTY_A_NAME}} shall promptly disclose all inventions, improvements, and discoveries made during the engagement.\n\n4. BACKGROUND IP CARVE-OUT\nBackground IP is listed in Exhibit {{IP_SCHEDULE}}. Items not listed are presumed Foreground IP. {{PARTY_A_NAME}} grants an irrevocable license to Background IP embedded in deliverables.\n\n5. MORAL RIGHTS WAIVER\n{{PARTY_A_NAME}} irrevocably waives all moral rights to the fullest extent permitted under federal and state law.\n\n6. POWER OF ATTORNEY\nIf {{PARTY_A_NAME}} is unavailable, {{PARTY_B_NAME}} is appointed attorney-in-fact to execute IP assignments on {{PARTY_A_NAME}}'s behalf. This power is irrevocable and coupled with an interest."},

    # ===== INDEMNIFICATION =====
    {"id": "INDEM_STD_US001", "clause_type": "indemnification", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "INDEMNIFICATION\n\n{{PARTY_A_NAME}} shall indemnify, defend, and hold harmless {{PARTY_B_NAME}} and its officers, directors, employees, and agents from and against any third-party claims, damages, losses, liabilities, and expenses (including reasonable attorneys' fees) arising from: (a) {{PARTY_A_NAME}}'s breach of this Agreement; (b) {{PARTY_A_NAME}}'s negligence or willful misconduct; (c) violation of applicable law by {{PARTY_A_NAME}}."},

    {"id": "INDEM_MOD_US001", "clause_type": "indemnification", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "INDEMNIFICATION\n\n1. MUTUAL INDEMNIFICATION\nEach Party (\"Indemnifying Party\") shall indemnify the other Party (\"Indemnified Party\") against third-party Claims arising from: (a) material breach; (b) negligence or willful misconduct; (c) violation of applicable law.\n\n2. IP INDEMNIFICATION\n{{PARTY_A_NAME}} shall additionally indemnify against Claims that the Deliverables infringe any US patent, copyright, or trade secret.\n\n3. PROCEDURE\nThe Indemnified Party shall: (a) provide prompt written notice; (b) grant sole control of defense and settlement; (c) provide reasonable cooperation. Failure to notify does not relieve the obligation unless materially prejudiced.\n\n4. EXCLUSIONS\nNo indemnification for Claims arising from: (a) Indemnified Party's modifications; (b) combination with non-provided materials; (c) continued use after notice of infringement.\n\n5. IP REMEDIES\nIf enjoined, {{PARTY_A_NAME}} shall: (a) obtain a license; (b) replace with non-infringing equivalent; or (c) refund fees paid for the infringing component."},

    {"id": "INDEM_STR_US001", "clause_type": "indemnification", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "INDEMNIFICATION\n\n1. BROAD INDEMNIFICATION\nEach Party indemnifies the other against all Claims, Losses, and Consequential Damages arising from: (a) any breach; (b) negligence, gross negligence, or willful misconduct; (c) violation of any law; (d) personal injury or property damage.\n\n2. IP INDEMNIFICATION (ENHANCED)\n{{PARTY_A_NAME}} indemnifies against all IP infringement Claims worldwide, including: patents (utility and design), copyrights, trademarks, trade dress, and trade secrets. Coverage is first-dollar with no deductible or threshold.\n\n3. DATA BREACH INDEMNIFICATION\n{{PARTY_A_NAME}} indemnifies against Claims arising from unauthorized access to or disclosure of personal data in {{PARTY_A_NAME}}'s possession, including regulatory fines, notification costs, and credit monitoring.\n\n4. DEFENSE OBLIGATION\nThe Indemnifying Party shall assume defense with counsel reasonably acceptable to the Indemnified Party. The Indemnified Party may engage separate counsel at its own expense.\n\n5. NO SETTLEMENT WITHOUT CONSENT\nNo settlement that imposes non-monetary obligations on the Indemnified Party without prior written consent.\n\n6. SURVIVAL\nIndemnification obligations survive termination for the applicable statute of limitations plus {{INDEMNITY_SURVIVAL_YEARS}} years."},

    # ===== LIMITATION OF LIABILITY =====
    {"id": "LIAB_STD_US001", "clause_type": "limitation-of-liability", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "LIMITATION OF LIABILITY\n\n1. CONSEQUENTIAL DAMAGES WAIVER\nIN NO EVENT SHALL EITHER PARTY BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, REGARDLESS OF THE CAUSE OF ACTION OR THEORY OF LIABILITY.\n\n2. AGGREGATE CAP\nEACH PARTY'S TOTAL AGGREGATE LIABILITY UNDER THIS AGREEMENT SHALL NOT EXCEED THE TOTAL FEES PAID OR PAYABLE DURING THE {{LIABILITY_CAP_PERIOD}} PRECEDING THE CLAIM.\n\n3. ESSENTIAL BASIS\nTHE LIMITATIONS IN THIS SECTION ARE AN ESSENTIAL ELEMENT OF THE BARGAIN AND SHALL APPLY REGARDLESS OF WHETHER THE REMEDIES AVAILABLE ARE ADEQUATE."},

    {"id": "LIAB_MOD_US001", "clause_type": "limitation-of-liability", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "LIMITATION OF LIABILITY\n\n1. CONSEQUENTIAL DAMAGES EXCLUSION\nNEITHER PARTY SHALL BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOST PROFITS, LOST DATA, OR BUSINESS INTERRUPTION.\n\n2. AGGREGATE CAP\nEACH PARTY'S TOTAL LIABILITY SHALL NOT EXCEED {{LIABILITY_CAP_MULTIPLIER}}x THE FEES PAID IN THE {{LIABILITY_CAP_PERIOD}} MONTHS PRECEDING THE CLAIM.\n\n3. SUPER CAP CARVE-OUTS\nThe following are not subject to the aggregate cap: (a) breach of confidentiality; (b) IP infringement indemnification; (c) willful misconduct or fraud; (d) personal injury.\n\n4. INSURANCE\nEach Party shall maintain commercially reasonable insurance coverage, including commercial general liability and professional liability (E&O) insurance.\n\n5. ESSENTIAL BASIS\nThese limitations reflect the allocation of risk and are a fundamental element of the consideration."},

    {"id": "LIAB_STR_US001", "clause_type": "limitation-of-liability", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "LIMITATION OF LIABILITY\n\n1. CONSEQUENTIAL DAMAGES\nNEITHER PARTY SHALL BE LIABLE FOR CONSEQUENTIAL, INDIRECT, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES.\n\n2. PER-INCIDENT AND AGGREGATE CAPS\n(a) Per-incident cap: {{PER_INCIDENT_CAP}} or fees paid in prior 3 months, whichever is greater;\n(b) Annual aggregate cap: {{LIABILITY_CAP_MULTIPLIER}}x annual fees;\n(c) Lifetime aggregate: {{LIFETIME_CAP_MULTIPLIER}}x total contract value.\n\n3. UNCAPPED OBLIGATIONS\nThe following obligations are not subject to any cap: (a) gross negligence or willful misconduct; (b) fraud or intentional misrepresentation; (c) death or personal injury; (d) breach of confidentiality involving trade secrets; (e) data breach indemnification.\n\n4. INSURANCE REQUIREMENTS\nEach Party shall maintain: (a) CGL: ${{CGL_COVERAGE}} per occurrence; (b) E&O/Professional Liability: ${{EO_COVERAGE}}; (c) Cyber Liability: ${{CYBER_COVERAGE}}; (d) Workers' Compensation: statutory limits. Certificates of insurance upon request.\n\n5. MITIGATION\nEach Party shall take commercially reasonable steps to mitigate damages."},

    # ===== REPRESENTATIONS AND WARRANTIES =====
    {"id": "WARR_STD_US001", "clause_type": "representations-and-warranties", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "REPRESENTATIONS AND WARRANTIES\n\nEach Party represents and warrants that: (a) it is duly organized and validly existing under the laws of its state of incorporation/formation; (b) it has full power and authority to enter into and perform this Agreement; (c) execution does not conflict with any other agreement; (d) it shall comply with all applicable federal, state, and local laws."},

    {"id": "WARR_MOD_US001", "clause_type": "representations-and-warranties", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "REPRESENTATIONS AND WARRANTIES\n\n1. MUTUAL REPRESENTATIONS\nEach Party represents: (a) valid organization and good standing; (b) authority to execute; (c) no conflicting obligations; (d) compliance with applicable laws including anti-corruption and export control.\n\n2. SERVICE PROVIDER WARRANTIES\n{{PARTY_A_NAME}} additionally warrants: (a) Services will be performed in a professional manner; (b) Deliverables will conform to specifications for {{WARRANTY_PERIOD}} days; (c) Deliverables will not infringe third-party IP rights; (d) it maintains adequate insurance.\n\n3. DISCLAIMER\nEXCEPT AS EXPRESSLY SET FORTH HEREIN, ALL WARRANTIES ARE DISCLAIMED, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT UNDER UCC §2-316.\n\n4. REMEDY\nFor warranty breach, {{PARTY_A_NAME}} shall re-perform or refund the applicable fees at {{PARTY_B_NAME}}'s election."},

    {"id": "WARR_STR_US001", "clause_type": "representations-and-warranties", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "REPRESENTATIONS AND WARRANTIES\n\n1. CORPORATE REPRESENTATIONS\nEach Party represents: (a) valid organization, good standing, and qualification in all necessary jurisdictions; (b) requisite corporate authority and all necessary approvals (board, shareholder); (c) execution does not violate charter documents, contracts, or laws.\n\n2. COMPLIANCE REPRESENTATIONS\nEach Party represents ongoing compliance with: (a) FCPA and anti-corruption laws; (b) export control and sanctions (EAR/ITAR/OFAC); (c) anti-money laundering (BSA); (d) employment and labor laws.\n\n3. FINANCIAL SOLVENCY\nEach Party represents that it is solvent, not subject to bankruptcy proceedings, and able to pay debts as they come due.\n\n4. SERVICE WARRANTIES\n{{PARTY_A_NAME}} warrants: (a) Services meet specifications for {{WARRANTY_PERIOD}} days post-delivery; (b) compliance with industry best practices; (c) no open-source software included without disclosure; (d) absence of malicious code.\n\n5. WARRANTY DISCLAIMER\nEXCEPT AS EXPRESSLY STATED, ALL OTHER WARRANTIES, EXPRESS OR IMPLIED (INCLUDING UCC §2-312 THROUGH §2-316), ARE DISCLAIMED.\n\n6. ONGOING DISCLOSURE\n{{PARTY_A_NAME}} shall promptly disclose any event that would make any representation materially inaccurate."},

    # ===== FORCE MAJEURE =====
    {"id": "FM_STD_US001", "clause_type": "force-majeure", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "FORCE MAJEURE\n\nNeither Party shall be liable for failure or delay in performance caused by events beyond its reasonable control, including acts of God, war, terrorism, fire, flood, earthquake, epidemic, government action, or labor disputes. The affected Party shall provide prompt written notice and use commercially reasonable efforts to mitigate the impact. If the force majeure event continues for more than {{FM_THRESHOLD_DAYS}} days, either Party may terminate this Agreement upon written notice."},

    {"id": "FM_MOD_US001", "clause_type": "force-majeure", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "FORCE MAJEURE\n\n1. DEFINED EVENTS\nForce Majeure Events include: (a) natural disasters (earthquake, hurricane, flood, wildfire); (b) pandemic or epidemic (including COVID-19 and variants); (c) war, terrorism, civil unrest, sanctions; (d) government orders, embargoes, trade restrictions; (e) cyberattacks (DDoS, ransomware) on critical infrastructure; (f) utility failures beyond the Party's control; (g) supply chain disruptions affecting critical components.\n\n2. OBLIGATIONS\nThe affected Party shall: (a) notify the other within {{FM_NOTICE_DAYS}} days; (b) provide regular status updates; (c) use commercially reasonable efforts to mitigate; (d) explore alternative means of performance.\n\n3. PAYMENT OBLIGATIONS\nPayment obligations for Services not rendered during the FM period are suspended proportionally.\n\n4. TERMINATION\nIf the FM event exceeds {{FM_THRESHOLD_DAYS}} days, either Party may terminate upon {{FM_TERMINATION_NOTICE}} days' notice without liability beyond amounts accrued."},

    {"id": "FM_STR_US001", "clause_type": "force-majeure", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "FORCE MAJEURE\n\n1. ENUMERATED EVENTS\nForce Majeure means: (a) acts of God; (b) pandemic/epidemic declared by WHO or CDC; (c) war, military action, terrorism; (d) cyberattacks, ransomware, nation-state attacks; (e) government actions, sanctions (OFAC), embargoes; (f) critical infrastructure failure; (g) supply chain collapse. Expressly excluded: (i) financial difficulty; (ii) market fluctuations; (iii) staffing shortages for non-pandemic reasons.\n\n2. NOTICE AND MITIGATION\n(a) Written notice within {{FM_NOTICE_DAYS}} days with detailed assessment;\n(b) Weekly status reports;\n(c) Activate Business Continuity Plan (BCP) within 48 hours;\n(d) Best efforts to implement alternative performance methods.\n\n3. BCP REQUIREMENTS\nEach Party shall maintain a tested BCP. Failure to maintain a BCP disqualifies a Party from invoking this clause.\n\n4. PHASED RESPONSE\n(a) Days 1-{{FM_PHASE1_DAYS}}: suspension with mitigation;\n(b) Days {{FM_PHASE1_DAYS}}-{{FM_THRESHOLD_DAYS}}: mandatory joint review and renegotiation;\n(c) Beyond {{FM_THRESHOLD_DAYS}} days: either Party may terminate.\n\n5. INSURANCE\nThe affected Party shall promptly file applicable insurance claims and share recovery with the other Party to the extent it offsets losses under this Agreement."},

    # ===== TERMINATION FOR CAUSE =====
    {"id": "TERMB_STD_US001", "clause_type": "termination-for-cause", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "TERMINATION FOR CAUSE\n\nEither Party may terminate this Agreement upon written notice if the other Party: (a) materially breaches this Agreement and fails to cure within {{CURE_PERIOD}} days after written notice specifying the breach; (b) becomes insolvent, files for bankruptcy under Title 11 of the U.S. Code, or has a receiver appointed for substantially all its assets."},

    {"id": "TERMB_MOD_US001", "clause_type": "termination-for-cause", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "TERMINATION FOR CAUSE\n\n1. MATERIAL BREACH\nEither Party may terminate upon {{CURE_PERIOD_STANDARD}} days' written notice if the breaching Party fails to cure. For payment defaults: {{CURE_PERIOD_SHORT}} days' cure.\n\n2. INSOLVENCY\nEither Party may terminate immediately if the other: (a) files a voluntary petition under 11 U.S.C.; (b) has an involuntary petition filed and not dismissed within 60 days; (c) makes an assignment for the benefit of creditors.\n\n3. SLA FAILURES\nIf {{PARTY_A_NAME}} fails to meet SLAs for {{CONSECUTIVE_FAILURES}} consecutive periods or {{CUMULATIVE_FAILURES}} periods in any 12-month period, {{PARTY_B_NAME}} may terminate for cause.\n\n4. REGULATORY CHANGE\nIf regulatory changes make performance unlawful, either Party may terminate upon {{REGULATORY_NOTICE_DAYS}} days' notice."},

    {"id": "TERMB_STR_US001", "clause_type": "termination-for-cause", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "TERMINATION FOR CAUSE\n\n1. MATERIAL BREACH\nBreach with {{CURE_PERIOD_STANDARD}} days' cure period. A second material breach of the same nature within 12 months is incurable and triggers immediate termination.\n\n2. AUTOMATIC TERMINATION TRIGGERS\nTermination is immediate (no cure) upon: (a) bankruptcy filing under 11 U.S.C.; (b) appointment of receiver or trustee; (c) fraud or criminal indictment; (d) breach of confidentiality or data protection obligations.\n\n3. SLA TERMINATION\n(a) {{CONSECUTIVE_SLA_FAILURES}} consecutive months of SLA failure;\n(b) Availability below {{OUTAGE_TERMINATION_THRESHOLD}}% in any single month;\n(c) Failure to implement remediation plan within {{REMEDIATION_PLAN_PERIOD}} days.\n\n4. REINSTATEMENT\nIf termination is withdrawn after cure, a reinstatement fee of ${{REINSTATEMENT_FEE}} applies.\n\n5. CROSS-DEFAULT\nMaterial breach of any other agreement between the Parties constitutes cause for termination under this Agreement."},

    # ===== TERMINATION FOR CONVENIENCE =====
    {"id": "TERMC_STD_US001", "clause_type": "termination-for-convenience", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "TERMINATION FOR CONVENIENCE\n\nEither Party may terminate this Agreement for any reason or no reason upon {{NOTICE_PERIOD}} days' prior written notice to the other Party. Upon termination, {{PARTY_B_NAME}} shall pay for all Services rendered through the effective date of termination."},

    {"id": "TERMC_MOD_US001", "clause_type": "termination-for-convenience", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "TERMINATION FOR CONVENIENCE\n\n1. NOTICE\nEither Party may terminate for convenience upon {{NOTICE_PERIOD_LONG}} days' written notice.\n\n2. WIND-DOWN\n{{PARTY_A_NAME}} shall: (a) complete work-in-progress to a reasonable stopping point; (b) deliver all completed Deliverables; (c) return all {{PARTY_B_NAME}} materials within {{RETURN_MATERIALS_DAYS}} days.\n\n3. PAYMENT\n{{PARTY_B_NAME}} shall pay: (a) all Services rendered through termination date; (b) WIP at the percentage of completion; (c) non-cancellable third-party costs reasonably incurred.\n\n4. TRANSITION ASSISTANCE\n{{PARTY_A_NAME}} shall provide transition assistance for up to {{TRANSITION_ASSISTANCE_DAYS}} days at then-current rates."},

    {"id": "TERMC_STR_US001", "clause_type": "termination-for-convenience", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "TERMINATION FOR CONVENIENCE\n\n1. DIFFERENTIATED NOTICE\n(a) {{PARTY_B_NAME}} (client) may terminate on {{CLIENT_NOTICE_PERIOD}} days' notice;\n(b) {{PARTY_A_NAME}} (provider) may terminate on {{VENDOR_NOTICE_PERIOD}} days' notice (longer period to protect client).\n\n2. EARLY TERMINATION FEES\nIf terminated before minimum commitment: (a) {{PARTY_B_NAME}} pays {{EARLY_TERMINATION_FEE_PERCENTAGE}}% of remaining contract value; (b) Minimum fee: ${{EARLY_TERMINATION_FEE}}.\n\n3. WIP SETTLEMENT\nUpon termination: (a) completed milestones: 100% payment; (b) WIP: {{WIP_PERCENTAGE}}% of milestone value; (c) valuation method: {{WIP_VALUATION_METHOD}}.\n\n4. MANDATORY TRANSITION\n(a) {{PARTY_A_NAME}} shall provide {{MINIMAL_TRANSITION_DAYS}} days' mandatory transition;\n(b) Transition rate: {{TRANSITION_RATE}};\n(c) Knowledge transfer includes documentation, training, and system access handover.\n\n5. DATA AND MATERIALS\nAll client data and materials returned within {{RETURN_PERIOD}} days with written certification of deletion."},

    # ===== EFFECT OF TERMINATION AND SURVIVAL =====
    {"id": "SURV_STD_US001", "clause_type": "effect-of-termination-and-survival", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "EFFECT OF TERMINATION AND SURVIVAL\n\n1. EFFECT\nUpon termination: (a) all rights and licenses terminate (except as expressly stated); (b) each Party shall return or destroy the other Party's Confidential Information; (c) all outstanding payment obligations become due.\n\n2. SURVIVAL\nThe following provisions survive termination: Confidentiality, Intellectual Property, Indemnification, Limitation of Liability, Governing Law, and Dispute Resolution."},

    {"id": "SURV_MOD_US001", "clause_type": "effect-of-termination-and-survival", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "EFFECT OF TERMINATION AND SURVIVAL\n\n1. IMMEDIATE EFFECTS\nUpon termination: (a) all licenses and access rights terminate within {{ACCESS_TERMINATION_DAYS}} days; (b) outstanding invoices for Services rendered become immediately due; (c) each Party returns the other's property and Confidential Information.\n\n2. TRANSITION\n{{PARTY_A_NAME}} shall: (a) provide {{TRANSITION_DAYS}} days of transition assistance; (b) deliver all completed and WIP deliverables; (c) transfer all client data in a commercially standard format.\n\n3. ACCRUED RIGHTS\nTermination does not affect rights or obligations accrued prior to the effective date, including warranty claims and indemnification obligations.\n\n4. SURVIVAL\nClauses that by their nature should survive shall survive indefinitely: Confidentiality, IP Ownership, Indemnification, Limitation of Liability, Governing Law, Dispute Resolution, and this clause."},

    {"id": "SURV_STR_US001", "clause_type": "effect-of-termination-and-survival", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "EFFECT OF TERMINATION AND SURVIVAL\n\n1. TERMINATION PROCEDURES\nWithin {{WIND_DOWN_DAYS}} days of termination notice: (a) cease new work immediately; (b) complete critical WIP to safe stopping points; (c) deliver all completed work product; (d) disable all system access; (e) return all materials and equipment.\n\n2. DATA HANDLING\n(a) All client data exported in open standard format within {{DATA_EXPORT_DAYS}} days;\n(b) Deletion of all copies within {{DATA_DELETION_DAYS}} days;\n(c) Written certification of deletion by an authorized officer.\n\n3. KNOWLEDGE TRANSFER\nMandatory knowledge transfer including: (a) documentation of all systems and processes; (b) training sessions for replacement personnel; (c) assistance with third-party vendor transitions.\n\n4. FINANCIAL SETTLEMENT\n(a) Final invoice within {{FINAL_INVOICE_DAYS}} days;\n(b) Reconciliation of prepaid amounts;\n(c) Refund of prepaid fees for undelivered Services within {{REFUND_DAYS}} days.\n\n5. SURVIVAL\nThe following survive indefinitely: Confidentiality (or until trade secrets become public), IP Ownership, Indemnification (for the applicable statute of limitations), Limitation of Liability, Governing Law, and Dispute Resolution. All other obligations survive for {{GENERAL_SURVIVAL_YEARS}} years."},

    # ===== NON-COMPETE =====
    {"id": "NONCOMP_STD_US001", "clause_type": "non-compete", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "NON-COMPETE\n\nDuring the term of this Agreement and for {{NON_COMPETE_PERIOD}} months thereafter, {{PARTY_A_NAME}} agrees not to directly engage in any business that competes with {{PARTY_B_NAME}}'s core business within {{GEOGRAPHIC_SCOPE}}. This restriction applies only to services substantially similar to those provided under this Agreement.\n\nNote: Enforceability varies by state. Some states (e.g., California under Business and Professions Code §16600) prohibit non-compete agreements. This clause is void where prohibited by applicable state law."},

    {"id": "NONCOMP_MOD_US001", "clause_type": "non-compete", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "NON-COMPETE\n\n1. RESTRICTION\nDuring the term and for {{NON_COMPETE_PERIOD}} months after termination, {{PARTY_A_NAME}} shall not: (a) directly or indirectly engage in a Competing Business; (b) own, manage, or operate a Competing Business; (c) serve as an officer, director, employee, or consultant of a Competing Business.\n\n2. DEFINITION\n\"Competing Business\" means any business providing {{COMPETING_SERVICES_DESCRIPTION}} within {{GEOGRAPHIC_SCOPE}}.\n\n3. CONSIDERATION\n{{PARTY_A_NAME}} acknowledges receiving adequate consideration for this restriction, including access to Confidential Information and specialized training.\n\n4. ENFORCEABILITY\nIf a court finds any restriction overbroad, the Parties request judicial reformation to the maximum enforceable scope per the applicable state's blue-pencil or reformation doctrine.\n\n5. STATE LAW LIMITATIONS\nThis clause shall not apply in states where non-competes are prohibited (including California, Minnesota, North Dakota, Oklahoma, and any state enacting similar legislation). In such states, the Confidentiality and Non-Solicitation clauses remain in full effect."},

    {"id": "NONCOMP_STR_US001", "clause_type": "non-compete", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "NON-COMPETE\n\n1. COMPREHENSIVE RESTRICTION\nDuring the term and for {{NON_COMPETE_PERIOD}} months post-termination, {{PARTY_A_NAME}} shall not, directly or indirectly: (a) engage in any Competing Business; (b) have any interest in a Competing Business (as owner, partner, shareholder, officer, director, employee, consultant, or otherwise); (c) assist any person in competing with {{PARTY_B_NAME}}.\n\n2. BROAD SCOPE\n\"Competing Business\" means any entity providing services or products substantially similar to those of {{PARTY_B_NAME}} anywhere within {{GEOGRAPHIC_SCOPE}}.\n\n3. LIQUIDATED DAMAGES\nBreach of this clause entitles {{PARTY_B_NAME}} to liquidated damages of ${{LIQUIDATED_DAMAGES_AMOUNT}} per violation, in addition to equitable relief.\n\n4. INJUNCTIVE RELIEF\n{{PARTY_A_NAME}} consents to specific performance and injunctive relief without bond in any court of competent jurisdiction.\n\n5. TOLLING\nThe non-compete period is tolled during any period of breach.\n\n6. ENFORCEABILITY AND REFORMATION\nIf unenforceable, court shall reform to maximum enforceable scope. California and other restrictive states: this clause does not apply; only Confidentiality and Non-Solicitation survive.\n\n7. FTC RULE\nThis clause is subject to the Federal Trade Commission's Non-Compete Clause Rule (16 CFR Part 910) if and when effective. Compliance modifications shall be made automatically."},

    # ===== NON-SOLICITATION =====
    {"id": "NONSOL_STD_US001", "clause_type": "non-solicitation", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "NON-SOLICITATION\n\nDuring the term and for {{NON_SOLICITATION_PERIOD}} months thereafter, neither Party shall directly solicit for employment or engagement any employee or contractor of the other Party who was involved in the performance of this Agreement. General advertisements and unsolicited applications are not considered solicitation."},

    {"id": "NONSOL_MOD_US001", "clause_type": "non-solicitation", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "NON-SOLICITATION\n\n1. EMPLOYEE NON-SOLICITATION\nDuring the term and for {{NON_SOLICITATION_PERIOD}} months post-termination, neither Party shall directly or indirectly solicit, recruit, or hire employees or contractors of the other Party who were: (a) involved in this Agreement; (b) introduced during the engagement.\n\n2. CLIENT NON-SOLICITATION\n{{PARTY_A_NAME}} shall not solicit or divert {{PARTY_B_NAME}}'s clients or prospects with whom {{PARTY_A_NAME}} had contact during the engagement for a period of {{CLIENT_NON_SOLICIT_PERIOD}} months.\n\n3. EXCEPTIONS\nGeneral advertisements, unsolicited applications, and use of third-party recruiters (not targeting the other Party) are permitted.\n\n4. REMEDY\nBreach entitles the non-breaching Party to equitable relief and recovery of recruitment/replacement costs."},

    {"id": "NONSOL_STR_US001", "clause_type": "non-solicitation", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "NON-SOLICITATION\n\n1. COMPREHENSIVE RESTRICTION\nDuring the term and {{NON_SOLICITATION_PERIOD}} months post-termination, neither Party shall directly or indirectly: (a) solicit, recruit, entice, or hire any employee, officer, or contractor; (b) encourage any such person to terminate their association; (c) hire any person who terminates within 6 months of termination (regardless of who initiated).\n\n2. CLIENT AND PROSPECT PROTECTION\n{{PARTY_A_NAME}} shall not solicit, divert, or transact with: (a) any client of {{PARTY_B_NAME}} encountered during the engagement; (b) any prospect in {{PARTY_B_NAME}}'s active pipeline.\n\n3. LOOKBACK\nRestrictions apply to persons associated with the other Party at any time during the {{LOOKBACK_MONTHS}}-month period preceding termination.\n\n4. LIQUIDATED DAMAGES\nBreach entitles the non-breaching Party to liquidated damages equal to the recruited person's annual compensation or ${{LIQUIDATED_DAMAGES_AMOUNT}}, whichever is greater.\n\n5. INJUNCTIVE RELIEF\nConsent to injunctive relief without bond."},

    # ===== NON-DISCLOSURE (EMPLOYMENT) =====
    {"id": "NDISC_STD_US001", "clause_type": "non-disclosure-employment", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "NON-DISCLOSURE (EMPLOYMENT)\n\nEmployee acknowledges access to Confidential Information and agrees: (a) to hold all Confidential Information in strict confidence; (b) not to disclose to any person outside the Company without prior written authorization; (c) to use Confidential Information solely to perform job duties; (d) to return all materials upon termination. This obligation survives employment for {{NDA_SURVIVAL_YEARS}} years. Trade secrets under the DTSA (18 U.S.C. §1836) are protected indefinitely."},

    {"id": "NDISC_MOD_US001", "clause_type": "non-disclosure-employment", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "NON-DISCLOSURE (EMPLOYMENT)\n\n1. SCOPE\nEmployee shall not disclose, publish, or use for personal benefit any Confidential Information, including: (a) trade secrets; (b) customer lists and data; (c) financial information; (d) product plans and roadmaps; (e) source code and algorithms; (f) business strategies.\n\n2. PERMITTED DISCLOSURES\nDisclosure is permitted: (a) as necessary in performance of duties; (b) with prior written approval; (c) as required by law or court order (with advance notice to the Company).\n\n3. DTSA WHISTLEBLOWER NOTICE\nPursuant to 18 U.S.C. §1833(b), Employee is notified that individuals may disclose trade secrets in confidence to government officials or attorneys for the sole purpose of reporting suspected violations of law.\n\n4. RETURN OF MATERIALS\nUpon termination, Employee shall return all materials, devices, and data within {{RETURN_PERIOD_DAYS}} days and provide certification of deletion.\n\n5. SURVIVAL\nObligations survive for {{NDA_SURVIVAL_YEARS}} years; trade secrets are protected in perpetuity."},

    {"id": "NDISC_STR_US001", "clause_type": "non-disclosure-employment", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "NON-DISCLOSURE (EMPLOYMENT)\n\n1. COMPREHENSIVE OBLIGATION\nEmployee shall maintain absolute confidentiality of all information learned during employment, whether marked confidential or not, that is not publicly available.\n\n2. SECURITY CONTROLS\nEmployee shall: (a) use Company-approved devices only; (b) not transfer data to personal devices; (c) use VPN and encryption for remote access; (d) report security incidents immediately.\n\n3. EXIT PROCEDURES\nUpon termination: (a) exit interview with confirmation of ongoing obligations; (b) return all physical and electronic materials within {{RETURN_PERIOD_DAYS}} days; (c) deletion certification with forensic verification upon Company request; (d) no retention of any copies.\n\n4. INJUNCTIVE RELIEF\nEmployee consents to injunctive relief (TRO, preliminary and permanent injunction) without the requirement of a bond.\n\n5. DTSA WHISTLEBLOWER NOTICE\nPursuant to 18 U.S.C. §1833(b)(1): immunity for whistleblower disclosures to government officials or attorneys.\n\n6. SURVIVAL\nObligations are perpetual for trade secrets. All other Confidential Information: {{NDA_SURVIVAL_YEARS}} years."},

    # ===== PARTIES AND RECITALS =====
    {"id": "PART_STD_US001", "clause_type": "parties-and-recitals", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "PARTIES AND RECITALS\n\nThis Agreement is entered into as of {{EFFECTIVE_DATE}} (the \"Effective Date\") by and between:\n\n{{PARTY_A_NAME}}, a {{PARTY_A_ENTITY_TYPE}} organized under the laws of the State of {{PARTY_A_STATE}}, with its principal place of business at {{PARTY_A_ADDRESS}} (\"{{PARTY_A_SHORT_NAME}}\"); and\n\n{{PARTY_B_NAME}}, a {{PARTY_B_ENTITY_TYPE}} organized under the laws of the State of {{PARTY_B_STATE}}, with its principal place of business at {{PARTY_B_ADDRESS}} (\"{{PARTY_B_SHORT_NAME}}\").\n\nWHEREAS, {{PARTY_A_SHORT_NAME}} desires to provide, and {{PARTY_B_SHORT_NAME}} desires to receive, certain services as described herein;\n\nNOW, THEREFORE, in consideration of the mutual covenants and agreements set forth herein, and for other good and valuable consideration, the receipt and sufficiency of which are hereby acknowledged, the Parties agree as follows:"},

    {"id": "PART_MOD_US001", "clause_type": "parties-and-recitals", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "PARTIES AND RECITALS\n\nThis Agreement is made effective as of {{EFFECTIVE_DATE}} by and between:\n\n{{PARTY_A_NAME}}, a {{PARTY_A_ENTITY_TYPE}} duly organized and existing under the laws of the State of {{PARTY_A_STATE}}, EIN: {{PARTY_A_EIN}}, with its principal office at {{PARTY_A_ADDRESS}} (\"{{PARTY_A_SHORT_NAME}}\"); and\n\n{{PARTY_B_NAME}}, a {{PARTY_B_ENTITY_TYPE}} duly organized and existing under the laws of the State of {{PARTY_B_STATE}}, EIN: {{PARTY_B_EIN}}, with its principal office at {{PARTY_B_ADDRESS}} (\"{{PARTY_B_SHORT_NAME}}\").\n\nRECITALS\n\nA. {{PARTY_A_SHORT_NAME}} is engaged in the business of {{PARTY_A_BUSINESS}}.\nB. {{PARTY_B_SHORT_NAME}} desires to engage {{PARTY_A_SHORT_NAME}} to provide certain services.\nC. The Parties wish to set forth the terms under which such services will be provided.\n\nIn consideration of the mutual promises, covenants, and conditions contained herein, and intending to be legally bound, the Parties agree as follows:"},

    {"id": "PART_STR_US001", "clause_type": "parties-and-recitals", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "PARTIES AND RECITALS\n\nThis Agreement is entered into as of the last date of signature below (the \"Effective Date\") by and between:\n\n{{PARTY_A_NAME}}, a {{PARTY_A_ENTITY_TYPE}} organized under the laws of the State of {{PARTY_A_STATE}}, in good standing, EIN: {{PARTY_A_EIN}}, registered with the Secretary of State, with its principal office at {{PARTY_A_ADDRESS}}, represented by {{PARTY_A_SIGNATORY}}, {{PARTY_A_SIGNATORY_TITLE}} (\"{{PARTY_A_SHORT_NAME}}\"); and\n\n{{PARTY_B_NAME}}, a {{PARTY_B_ENTITY_TYPE}} organized under the laws of the State of {{PARTY_B_STATE}}, in good standing, EIN: {{PARTY_B_EIN}}, with its principal office at {{PARTY_B_ADDRESS}}, represented by {{PARTY_B_SIGNATORY}}, {{PARTY_B_SIGNATORY_TITLE}} (\"{{PARTY_B_SHORT_NAME}}\").\n\nRECITALS\n\nA. {{PARTY_A_SHORT_NAME}} is engaged in {{PARTY_A_BUSINESS}} and possesses the requisite expertise, licenses, and qualifications.\nB. {{PARTY_B_SHORT_NAME}} has conducted due diligence and wishes to engage {{PARTY_A_SHORT_NAME}}.\nC. Each signatory represents they have full corporate authority to execute this Agreement, and all necessary board approvals have been obtained.\n\nNOW, THEREFORE, in consideration of the premises and the mutual covenants set forth herein, and intending to be legally bound hereby, the Parties agree:"},

    # ===== ENTIRE AGREEMENT =====
    {"id": "ENTIRE_STD_US001", "clause_type": "entire-agreement-amendments-severability", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "ENTIRE AGREEMENT; AMENDMENTS; SEVERABILITY\n\n1. ENTIRE AGREEMENT\nThis Agreement constitutes the entire agreement between the Parties and supersedes all prior negotiations, representations, and agreements, whether written or oral.\n\n2. AMENDMENTS\nThis Agreement may be amended only by a written instrument signed by both Parties.\n\n3. SEVERABILITY\nIf any provision is held invalid or unenforceable, the remaining provisions continue in full force and effect."},

    {"id": "ENTIRE_MOD_US001", "clause_type": "entire-agreement-amendments-severability", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "ENTIRE AGREEMENT; AMENDMENTS; SEVERABILITY\n\n1. INTEGRATION\nThis Agreement, together with all Exhibits, Schedules, and SOWs, constitutes the entire agreement and supersedes all prior understandings, proposals, and agreements. No prior course of dealing or trade usage modifies this Agreement.\n\n2. AMENDMENTS\nAmendments must be in writing and signed by authorized representatives of both Parties. Email exchanges do not constitute amendments unless expressly so stated.\n\n3. WAIVER\nFailure to enforce any provision does not constitute a waiver. Waivers are effective only if in writing.\n\n4. SEVERABILITY\nIf any provision is held invalid, the court shall reform it to the minimum extent necessary. Invalid provisions do not affect the validity of remaining provisions.\n\n5. COUNTERPARTS\nThis Agreement may be executed in counterparts, each constituting an original. Electronic signatures (per the E-SIGN Act or UETA) are binding."},

    {"id": "ENTIRE_STR_US001", "clause_type": "entire-agreement-amendments-severability", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "ENTIRE AGREEMENT; AMENDMENTS; SEVERABILITY\n\n1. INTEGRATION\nThis Agreement (including all Exhibits, Schedules, SOWs, and amendments) constitutes the entire agreement. All prior negotiations, MoUs, term sheets, communications, and agreements are superseded and of no further legal effect.\n\n2. PAROL EVIDENCE\nNo evidence of prior or contemporaneous oral agreements or representations shall be admissible to vary, contradict, or supplement this Agreement.\n\n3. AMENDMENTS\n(a) Amendments must be in writing, signed by authorized officers;\n(b) Material amendments (affecting scope, price, or term >10%) require board-level approval;\n(c) An amendment register shall be maintained listing all amendments.\n\n4. WAIVER\nAll waivers must be in writing. A waiver of one breach does not waive future breaches. No course of performance constitutes a waiver.\n\n5. SEVERABILITY\nIf any provision is held unenforceable: (a) the court shall reform to the maximum enforceable extent; (b) if reformation is not possible, the provision is severed; (c) remaining provisions continue in full effect.\n\n6. ORDER OF PRECEDENCE\nIn case of conflict: (a) amendments (in reverse chronological order); (b) main body; (c) Exhibits; (d) SOWs."},

    # ===== PROFIT SHARING =====
    {"id": "PROFIT_STD_US001", "clause_type": "profit-sharing-terms", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "PROFIT SHARING AND DISTRIBUTION\n\n1. PROFIT/LOSS ALLOCATION\nNet profits and losses shall be allocated among Partners in the ratio of {{PROFIT_SHARE_RATIO}}, in accordance with the IRC §704(b) substantial economic effect requirements.\n\n2. DISTRIBUTION SCHEDULE\nDistributions shall be made {{DISTRIBUTION_FREQUENCY}} within {{DISTRIBUTION_DAYS}} days after the close of each period, subject to maintaining adequate working capital.\n\n3. TAX DISTRIBUTIONS\nThe Partnership shall distribute sufficient funds to each Partner to cover estimated federal and state income tax liabilities on allocated income (\"Tax Distributions\") on a quarterly basis.\n\n4. CAPITAL ACCOUNTS\nCapital accounts shall be maintained per IRC §704(b) and Treasury Regulation §1.704-1(b)(2)(iv).\n\n5. DRAWING RIGHTS\nPartners may draw up to ${{MAX_DRAW_AMOUNT}} per {{DRAW_PERIOD}} against anticipated profits, subject to managing partner approval."},

    {"id": "PROFIT_MOD_US001", "clause_type": "profit-sharing-terms", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "PROFIT SHARING AND DISTRIBUTION\n\n1. ALLOCATION\nProfits and losses allocated per {{PROFIT_SHARE_RATIO}}, compliant with IRC §704(b) substantial economic effect rules. Special allocations require unanimous consent and tax advisor review.\n\n2. DISTRIBUTIONS\n(a) {{DISTRIBUTION_FREQUENCY}} distributions within {{DISTRIBUTION_DAYS}} days;\n(b) Minimum reserve of ${{MIN_RESERVE_AMOUNT}} maintained before distributions;\n(c) Tax distributions quarterly per estimated federal/state rates.\n\n3. CAPITAL ACCOUNTS\nMaintained per Treasury Reg. §1.704-1(b)(2)(iv). Annual fair market value adjustments per §704(b) revaluation events.\n\n4. ADDITIONAL CONTRIBUTIONS\n(a) {{CAPITAL_CALL_NOTICE_DAYS}} days' notice;\n(b) Approval by {{CAPITAL_CALL_APPROVAL_THRESHOLD}}% of capital;\n(c) Interest on excess contributions at {{CAPITAL_INTEREST_RATE}}% (AFR-compliant).\n\n5. K-1 AND TAX REPORTING\nThe Partnership shall furnish Schedule K-1 (Form 1065) to each Partner by March 15 (or the applicable extended deadline) each year."},

    {"id": "PROFIT_STR_US001", "clause_type": "profit-sharing-terms", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "PROFIT SHARING AND DISTRIBUTION\n\n1. WATERFALL DISTRIBUTION\nNet profits distributed: (a) Return of capital contributions; (b) Preferred return at {{PREFERRED_RETURN_RATE}}% (IRC §707(c) guaranteed payments if applicable); (c) Carried interest of {{CARRY_PERCENTAGE}}% to Managing Partner; (d) Balance per {{PROFIT_SHARE_RATIO}}.\n\n2. SUBSTANTIAL ECONOMIC EFFECT\nAll allocations comply with IRC §704(b) and Treasury Reg. §1.704-1(b). QIO and minimum gain chargeback provisions included per §704(b) safe harbor.\n\n3. DISTRIBUTION CONTROLS\n(a) {{DISTRIBUTION_FREQUENCY}} distributions subject to minimum reserve of ${{MIN_RESERVE_AMOUNT}} or {{RESERVE_PERCENTAGE}}% of revenue;\n(b) No distributions during material breach;\n(c) Disputed amounts held in escrow.\n\n4. CAPITAL CALL DEFAULT\nFailure to fund within {{CAPITAL_CURE_PERIOD_DAYS}} days: (a) proportional dilution; (b) default interest at {{DEFAULT_INTEREST_RATE}}% (AFR + 4%).\n\n5. CLAWBACK\nExcess distributions subject to clawback within {{CLAWBACK_PERIOD_DAYS}} days with interest.\n\n6. TAX MATTERS PARTNER\nThe Managing Partner serves as Tax Matters Partner (or Partnership Representative under the BBA regime, IRC §6223). Partnership-level audits and adjustments under the centralized audit regime."},

    # ===== DATA PROCESSING OBLIGATIONS =====
    {"id": "DPA_STD_US001", "clause_type": "data-processing-obligations", "variant": "Standard", "jurisdiction": "US", "risk_level": "Low",
     "raw_text": "DATA PROCESSING OBLIGATIONS\n\n1. SCOPE\nProcessor shall process Personal Information only as directed by Controller and solely for the purposes of this Agreement.\n\n2. APPLICABLE LAW\nProcessor shall comply with applicable US data protection laws, including CCPA/CPRA (Cal. Civ. Code §1798.100 et seq.) and applicable state privacy laws.\n\n3. SECURITY\nProcessor shall implement reasonable security measures consistent with industry standards, including encryption, access controls, and employee training.\n\n4. BREACH NOTIFICATION\nProcessor shall notify Controller of any Security Breach within {{BREACH_NOTIFICATION_HOURS}} hours of discovery, consistent with applicable state breach notification laws.\n\n5. DATA RETURN\nUpon termination, Processor shall delete or return all Personal Information within {{DATA_DELETION_DAYS}} days."},

    {"id": "DPA_MOD_US001", "clause_type": "data-processing-obligations", "variant": "Moderate", "jurisdiction": "US", "risk_level": "Medium",
     "raw_text": "DATA PROCESSING OBLIGATIONS\n\n1. PROCESSING SCOPE\nProcessor acts as a \"Service Provider\" (CCPA) or \"Processor\" (state laws) and shall process Personal Information only per Controller's documented instructions.\n\n2. MULTI-STATE COMPLIANCE\nProcessor shall comply with: (a) CCPA/CPRA (California); (b) VCDPA (Virginia); (c) CPA (Colorado); (d) CTDPA (Connecticut); (e) all other applicable state privacy laws.\n\n3. SECURITY MEASURES\n(a) SOC 2 Type II certification or equivalent;\n(b) Encryption (AES-256 at rest, TLS 1.2+ in transit);\n(c) Annual penetration testing;\n(d) Employee background checks and security training.\n\n4. BREACH NOTIFICATION\n(a) Notify Controller within {{BREACH_NOTIFICATION_HOURS}} hours;\n(b) Include: nature, affected individuals, mitigation measures;\n(c) Cooperate with Controller for state AG notifications.\n\n5. SUB-PROCESSORS\n(a) Current list in {{SUB_PROCESSOR_SCHEDULE}};\n(b) {{SUB_PROCESSOR_OBJECTION_DAYS}} days for objection to new sub-processors.\n\n6. DATA SUBJECT RIGHTS\nProcessor shall assist with consumer rights requests (access, deletion, opt-out of sale/sharing) within statutory timeframes.\n\n7. DATA RETURN AND DELETION\nReturn or delete within {{DATA_DELETION_DAYS}} days with written certification."},

    {"id": "DPA_STR_US001", "clause_type": "data-processing-obligations", "variant": "Strict", "jurisdiction": "US", "risk_level": "High",
     "raw_text": "DATA PROCESSING OBLIGATIONS\n\n1. ROLE AND RESTRICTIONS\nProcessor is a \"Service Provider\" under CCPA §1798.140(ag) and shall not: (a) sell or share Personal Information; (b) retain, use, or disclose PI for any purpose other than performing Services; (c) combine PI with other sources except as permitted.\n\n2. COMPREHENSIVE COMPLIANCE\nCompliance required with all applicable federal and state laws including CCPA/CPRA, VCDPA, CPA, CTDPA, HIPAA (if applicable), GLBA (if applicable), COPPA (if applicable), and FTC Act §5.\n\n3. ENHANCED SECURITY\n(a) SOC 2 Type II and ISO 27001;\n(b) AES-256 encryption, TLS 1.3;\n(c) Zero-trust architecture;\n(d) Quarterly penetration testing;\n(e) 24/7 SOC monitoring;\n(f) Annual third-party security audit.\n\n4. BREACH RESPONSE\n(a) Notification within {{BREACH_NOTIFICATION_HOURS}} hours;\n(b) Forensic investigation report within {{INCIDENT_REPORT_DAYS}} days;\n(c) Processor bears all breach notification costs, credit monitoring, and remediation;\n(d) Liquidated damages: ${{BREACH_LIABILITY_AMOUNT}} per incident.\n\n5. SUB-PROCESSOR GOVERNANCE\n(a) Prior written approval required;\n(b) Flow-down of equivalent obligations;\n(c) Removal within {{SUB_PROCESSOR_REMOVAL_DAYS}} days at Controller's request.\n\n6. AUDIT RIGHTS\n(a) Annual audit with {{AUDIT_NOTICE_DAYS}} days' notice;\n(b) Emergency audit without notice post-breach;\n(c) Evidence provided within {{AUDIT_RESPONSE_DAYS}} days.\n\n7. DATA LIFECYCLE\n(a) Automated retention policies;\n(b) Deletion within {{DATA_DELETION_DAYS}} days of termination;\n(c) NIST 800-88-compliant media sanitization;\n(d) Backup purge within {{BACKUP_PURGE_DAYS}} days."},
]


def phase6(session):
    print("\n=== PHASE 6: US Jurisdiction Clauses ===\n")

    created = 0
    skipped = 0
    for clause in US_CLAUSES:
        r = session.run("MATCH (c:Clause {id: $id}) RETURN count(*) AS cnt", {"id": clause["id"]})
        if r.single()["cnt"] > 0:
            skipped += 1
            continue

        # Create clause node
        session.run("""
            CREATE (c:Clause {
                id: $id, clause_type: $clause_type, name: $name,
                variant: $variant, jurisdiction: $jurisdiction,
                risk_level: $risk_level, raw_text: $raw_text
            })
        """, {**clause, "name": f"{clause['clause_type']} — {clause['variant']} (US)"})

        # HAS_VARIANT edge
        session.run("""
            MATCH (ct:ClauseType {id: $ct_id}), (c:Clause {id: $c_id})
            CREATE (ct)-[:HAS_VARIANT]->(c)
        """, {"ct_id": clause["clause_type"], "c_id": clause["id"]})

        # GOVERNED_BY edge
        session.run("""
            MATCH (c:Clause {id: $c_id}), (j:Jurisdiction {id: 'us'})
            CREATE (c)-[:GOVERNED_BY]->(j)
        """, {"c_id": clause["id"]})

        created += 1

    print(f"  Created {created} clause nodes, skipped {skipped}")

    # Create CONFLICTS_WITH edges between US variants (same pattern as India)
    print("\n  Creating US CONFLICTS_WITH edges...")
    for v1, v2, severity in [("Standard", "Moderate", "medium"), ("Standard", "Strict", "high"), ("Moderate", "Strict", "high")]:
        for a_var, b_var in [(v1, v2), (v2, v1)]:
            result = session.run("""
                MATCH (a:Clause), (b:Clause)
                WHERE a.clause_type = b.clause_type
                  AND a.variant = $a_var AND b.variant = $b_var
                  AND a.jurisdiction = 'US' AND b.jurisdiction = 'US'
                  AND NOT (a)-[:CONFLICTS_WITH]->(b)
                CREATE (a)-[:CONFLICTS_WITH {
                    severity: $severity, conflict_type: 'duplication',
                    reason: 'Cannot have both ' + a.variant + ' and ' + b.variant + ' variants of ' + a.clause_type + ' in one contract',
                    resolution_advice: 'Choose one variant'
                }]->(b)
                RETURN count(*) AS cnt
            """, {"a_var": a_var, "b_var": b_var, "severity": severity})
            cnt = result.single()["cnt"]
            if cnt > 0:
                print(f"    ✓ {a_var}→{b_var} ({severity}): {cnt} edges")

    # Create ALTERNATIVE_TO edges for US
    print("\n  Creating US ALTERNATIVE_TO edges...")
    alt_config = [
        ("Standard", "Moderate", "enhanced_protection", "medium"),
        ("Standard", "Strict", "maximum_protection", "low"),
        ("Moderate", "Standard", "simplified", "medium"),
        ("Moderate", "Strict", "enhanced_enforcement", "low"),
        ("Strict", "Moderate", "balanced_approach", "high"),
        ("Strict", "Standard", "simplified", "high"),
    ]
    for v1, v2, alt_type, strength in alt_config:
        result = session.run("""
            MATCH (a:Clause), (b:Clause)
            WHERE a.clause_type = b.clause_type
              AND a.variant = $v1 AND b.variant = $v2
              AND a.jurisdiction = 'US' AND b.jurisdiction = 'US'
              AND NOT (a)-[:ALTERNATIVE_TO]->(b)
            CREATE (a)-[:ALTERNATIVE_TO {
                alternative_type: $alt_type,
                recommendation_strength: $strength,
                reason: $v2 + ' variant offers an alternative level of protection under US law',
                benefit: 'Alternative ' + $v2 + ' level of contractual protection'
            }]->(b)
            RETURN count(*) AS cnt
        """, {"v1": v1, "v2": v2, "alt_type": alt_type, "strength": strength})
        cnt = result.single()["cnt"]
        if cnt > 0:
            print(f"    ✓ {v1}→{v2}: {cnt} edges")

    # Wire CONTAINS_PARAM for US clauses (reuse existing parameters)
    print("\n  Wiring US CONTAINS_PARAM edges (reusing existing parameters)...")
    # Map US clause IDs to the same params as their India counterparts
    r = session.run("""
        MATCH (c:Clause)-[:CONTAINS_PARAM]->(p:Parameter)
        WHERE c.jurisdiction = 'India'
        RETURN c.id AS india_id, c.clause_type AS ct, c.variant AS v, collect(p.id) AS param_ids
    """)
    india_params = {}
    for rec in r:
        key = (rec["ct"], rec["v"])
        india_params[key] = rec["param_ids"]

    param_edges_created = 0
    for clause in US_CLAUSES:
        key = (clause["clause_type"], clause["variant"])
        if key in india_params:
            for pid in india_params[key]:
                session.run("""
                    MATCH (c:Clause {id: $cid}), (p:Parameter {id: $pid})
                    WHERE NOT (c)-[:CONTAINS_PARAM]->(p)
                    CREATE (c)-[:CONTAINS_PARAM]->(p)
                """, {"cid": clause["id"], "pid": pid})
                param_edges_created += 1

    print(f"    ✓ Created {param_edges_created} CONTAINS_PARAM edges")

    print("\n✅ Phase 6 complete!")


if __name__ == "__main__":
    with driver.session() as session:
        phase6(session)
    driver.close()
